name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: ${{ github.workspace }}/.cargo

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: |
          rustc --version
          cargo --version
          cargo test --verbose

  build:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build release binary
        run: |
          rustc --version
          cargo --version
          cargo build --release

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp target/release/xperformance artifacts/
          cp README.md artifacts/
          cp README_zh.md artifacts/
          cp LICENSE artifacts/
          cd artifacts
          tar -czf xtools-linux-x86_64.tar.gz *

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xtools-linux-x86_64
          path: artifacts/xtools-linux-x86_64.tar.gz
          retention-days: 0  # Keep forever

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: xtools-linux-x86_64
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: artifacts/xtools-linux-x86_64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true